# Basic provisioning example
- name: Ansible test
  hosts: localhost
  vars_files:
    - secrets.yml
  tasks:
    - name: Provision ec2 instance
      ec2:
        key_name: demo
        instance_type: t2.micro
        image: ami-0dacb0c129b49f529
        region: us-east-2
        wait: yes
        group: Ansible
        count: 1
        vpc_subnet_id: subnet-0b255e0da4867c08f
        assign_public_ip: yes
        aws_access_key: "{{ aws_access_key_id }}" 
        aws_secret_key: "{{ aws_secret_access_key }}"
